# Generated by Django 4.2.8 on 2023-12-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('in_price', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('in_stock', models.CharField(max_length=10)),
                ('unit', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
