# Generated by Django 4.2.8 on 2023-12-06 17:55

from django.db import migrations

priceListItems = [
  {
    'id': 1,
    'article_number': 123,
    'name': "Computer",
    'in_price': 50000,
    'price': 70000,
    'in_stock': "Yes",
    'unit': 100,
    'description': "HP Computer",
  },
  {
    'id': 2,
    'article_number': 127,
    'name': "Laptop",
    'in_price': 60000,
    'price': 90000,
    'in_stock': "Yes",
    'unit': 145,
    'description': "Acer Laptop",
  },
]

def populateTables(apps, schema_editor):
  PriceListItems = apps.get_model('pricelist', 'PriceListItems')

  for pli in priceListItems:
    p = PriceListItems(article_number=pli['article_number'],
                       name=pli['name'],
                       in_price=pli['in_price'],
                       price=pli['price'],
                       in_stock=pli['in_stock'],
                       unit=pli['unit'],
                       description=pli['description'])
    p.save()

class Migration(migrations.Migration):
  dependencies = [
      ('pricelist', '0001_initial'),
  ]

  operations = [
      migrations.RunPython(populateTables)
  ]
