# Generated by Django 4.2.8 on 2023-12-06 17:55

from django.db import migrations

terms = [
  {'key': 'terms', 'value': 'Terms'},
  {'key': 'terms_text_1', 'value': 'BY clicking on Invoicing Now you choose to download according to the information you have entered and the text on the download page and the terms here, and at the same time accept the terms here.'},
  {'key': 'terms_text_2', 'value': 'You can use the program FREE for 14 days.'},
  {'key': 'terms_text_3', 'value': 'LettFaktura is so easy and self-explanatory that the chance that you will end up needing support is minimal, but if you should need support, we are here for you, with our office staffed most of the day. After the trial period, the subscription continues and costs NOK 99, for example. VAT per month, which is invoiced annually. If you do not wish to keep the program, simply cancel the trial period by notifying us within 14 days of downloading.'},
  {'key': 'terms_text_4', 'value': 'You of course have the right to end the use of the program free of charge, by notifying us by email within 14 days of download, that you do not wish to continue with the program, and of course not paying anything either.'},
  {'key': 'terms_text_5', 'value': 'If we do not receive such a message from you within 14 days of downloading, then the order cannot be changed for natural reasons. By download is meant the date and time when you have chosen to press the Invoicing Now button.'},
  {'key': 'terms_text_6', 'value': 'Invoicing is done for one year at a time.'},
  {'key': 'terms_text_7', 'value': 'The price for LettFaktura (offer price NOK 99 per month / word price NOK 129 per month) is for the annual fee Start for one year of use of the program.'},
  {'key': 'terms_text_8', 'value': '(When using the offer price of NOK 99, the one-year period is calculated from download.)'},
  {'key': 'terms_text_9', 'value': 'All prices are ex. VAT.'},
  {'key': 'terms_text_10', 'value': 'Time registration. Calculation, Member invoicing, Offers, Customer follow-up, Inventory count, Inventory management and English invoice text are additional modules that can be ordered after installation of the program.'},
  {'key': 'terms_text_11', 'value': 'The annual fee is ongoing, but if you do not wish to continue using the program, all you have to do is give notice thirty days before the start of the next one-year period.'},
  {'key': 'terms_text_12', 'value': 'The introductory offer (NOK 99 per month) is for the annual fee Start for the first year. After the first year, words are billed. price which is currently, for annual fee Start, one hundred and twenty-nine kroner per month, for annual fee Remote control, two hundred and sixty-five kroner per month and for annual fee Pro, three hundred and thirty-three kroner per month. After one year, the annual Remote Control fee is invoiced as standard, but you can choose Start or Pro by giving notice at any time before the due date.'},
  {'key': 'terms_text_13', 'value': 'If you choose to keep the program by not notifying us by email within 14 days of download that you do not wish to continue with the program, you accept that you will pay the invoice for your order. Code for the program will be sent automatically after the invoice has been paid. Failure to pay the invoice or late payment does not give the right to cancel the order. We are happy to help fix the logo for you at cost price.'},
  {'key': 'terms_text_14', 'value': 'Licenses for the use of LettFaktura are of course sold in accordance with the applicable laws.'},
  {'key': 'terms_text_15', 'value': 'In order to be able to help you more easily and provide you with support, as well as to comply with the laws, we naturally have to store your information.'},
  {'key': 'terms_text_16', 'value': 'In connection with the storage of information, the law requires that we provide you with the following information:'},
  {'key': 'terms_text_17', 'value': "If you order as a private person, you have the right to cancel as required by law. Your information is stored so that we can help you, etc. We will use it to be able to help you if you need help, follow the laws regarding bookkeeping, etc. When there are upgrades and the like, we may send you offers and the like about our products and services by email or the like. You may be contacted by email, post and phone. If you don't want to be contacted, just send us an email about it."},
  {'key': 'terms_text_18', 'value': 'You can at any time ask not to be sent information about upgrades by email, fax, letter or the like, and we will of course not do that. You send such a request to us by email, fax, letter or similar.'},
  {'key': 'terms_text_19', 'value': 'For natural reasons, we have to store, process and move your data. Your information is stored until further notice. You give us permission to store, process and move your data, as well as to send you offers and the like by email, fax, letter and the like. Due to the way it works with software, permission also needs to be given to other parties. The permission is therefore granted to us, as well as to the companies and/or person(s) who own the software, the source code, the website and the like. It is also given to current and future companies owned and/or controlled by one or more of those who currently own and/or control us. It is also given to current and future companies owned and/or controlled by one or more of those who currently own and/or control the companies (if any), which own or will own the software, source code, website and the like. It is also given to current and future persons (if any) who own or will own the software, source code, website and the like. This applies both to current and future products and services. It is also given to another company, which we can use to send/sell products, upgrades and the like, either by sub-licensing or in another way.'},
  {'key': 'terms_text_20', 'value': 'Of course, you have the right to request access to, change and deletion of the information we hold about you. You also have the right to request restriction of data processing, and to object to data processing and the right to data portability. You have the right to complain to the supervisory authority. You can find more legal information about us here. The laws of Ireland are the applicable laws. Placing an order is of course completely voluntary. Of course, we do not use any automated profiling or decisions.'},
  {'key': 'terms_text_21', 'value': 'If you wish to contact us, please use the information on this or any of our other websites.'},
  {'key': 'terms_text_22', 'value': 'Click on Invoicing Now to download according to the information you have entered and the terms here. (Date and time of admission are entered automatically in our registers.)'},
  {'key': 'terms_text_23', 'value': 'Our experience is that our customers are very satisfied with the way we work and hope and believe that this will also be their experience.'},
  {'key': 'terms_text_24', 'value': 'Have a great day!'},
  {'key': 'close', 'value': 'Close and Go Back'}
]

uss = [
  {'key': 'us_text_1', 'value': 'We that dispose of and drive this homepage and that also sell the programs that are sold on this homepage are: Lettfaktura Ltd, registered in Ireland with company number 638535. Registered office is in Co. Laois, Ireland.'},
  {'key': 'us_text_2', 'value': 'We hope that you will have much joy and use of our homepage.'},
  {'key': 'us_text_3', 'value': 'Have a still great day!'},
  {'key': 'close', 'value': 'Close and Go Back'},
]

navigations = [
  {'key': 'home', 'name': "Home", 'link': '/home'},
  {'key':'order', 'name': "Order", 'link': '/order'},
  {'key':'our_customer', 'name': "Our Customers", 'link': '/our_customer'},
  {'key':'about_us', 'name': "About Us", 'link': '/about_us'},
  {'key':'contact_us', 'name': "Contact Us", 'link': '/contact_us'},
  {'key': 'logo', 'name': 'Logo', 'link': 'https://storage.123fakturere.no/public/icons/diamond.png'}
]

pricelists = [
  {'key': 'no_products', 'value': "No Product"},
  {'key': 'add_product_now', 'value': "Add Product"},
  {'key': 'new_product', 'value': "New Product"},
  {'key': 'print_list', 'value': "Print List"},
  {'key': 'article_number', 'value': "Article No."},
  {'key': 'product_or_service', 'value': "Product / Service"},
  {'key': 'in_price', 'value': "In Price"},
  {'key': 'price', 'value': "Price"},
  {'key': 'in_stock', 'value': "In Stock"},
  {'key': 'unit', 'value': "Unit"},
  {'key': 'description', 'value': "Description"},
  {'key': 'article_number_placeholder', 'value': "Enter article number"},
  {'key': 'product_service_placeholder', 'value': "Enter product name"},
  {'key': 'in_price_placeholder', 'value': "Enter in price"},
  {'key': 'price_placeholder', 'value': "Enter price"},
  {'key': 'in_stock_placeholder', 'value': "Enter stock"},
  {'key': 'unit_placeholder', 'value': "Enter unit"},
  {'key': 'description_placeholder', 'value': "Enter description"},
  {'key': 'save', 'value': "Save"},
  {'key': 'close', 'value': "Close"},
  {'key': 'search_article_number', 'value': "Search Article No .."},
  {'key': 'search_product', 'value': "Search Product .."},
  {'key': 'advanced_mode', 'value': "Advanced Mode"},
  {'key': 'advanced_mode_text_1', 'value': "In advanced mode - Unit - you have a dedicated field for unit on the invoices and price list."},
  {'key': 'advanced_mode_text_2', 'value': "In advanced mode - Full - you have a dedicated field for article number and for unit on the invoices and price list."},
  {'key': 'advanced_mode_text_3', 'value': "It is only recommended to use Advanced mode - Full if you need to use article number, as it will impact the layout of the invoice to a great degree, as a lot more information is needed on the invoice. [THIS IS FOR TEST]"},
  {'key': 'advanced_mode_text_4', 'value': "For most users - Ordinary mode - (and for some, Advanced mode - Unit) is the best option to use."},
  {'key': 'ordinary_mode', 'value': "Ordinary Mode"},
  {'key': 'advanced_mode_unit', 'value': "Advanced Mode - Unit"},
  {'key': 'advanced_mode_full', 'value': "Advanced Mode - Full"},
  {'key': 'user_name', 'value': 'Prakhar Pandey'},
  {'key': 'user_address', 'value': 'New Delhi'},
  {'key': 'user_profile_pic', 'value': 'https://storage.123fakturere.no/public/icons/diamond.png'}
]

def populateTables(apps, schema_editor):
  Terms = apps.get_model('language', 'Terms')
  Us = apps.get_model('language', 'Us')
  Navigation = apps.get_model('language', 'Navigation')
  PriceListInfo = apps.get_model('language', 'PriceListInfo')

  for term in terms:
    t = Terms(key=term['key'], value=term['value'])
    t.save()

  for us in uss:
    u = Us(key=us['key'], value=us['value'])
    u.save()

  for navigation in navigations:
    n = Navigation(key=navigation['key'], name=navigation['name'], link=navigation['link'])
    n.save()

  for pricelist in pricelists:
    p = PriceListInfo(key=pricelist['key'], value=pricelist['value'])
    p.save()

class Migration(migrations.Migration):
  dependencies = [
      ('language', '0001_initial'),
  ]

  operations = [
      migrations.RunPython(populateTables)
  ]
